### ISSUE TITLE
Improve first-time contributor onboarding experience

### ISSUE THREAD

**Issue by imballinst** [Manuel-Leleuly/simple-iam#1]
Hey @Manuel-Leleuly, hope you are doing well!

I noticed the following development requirements in the README:

1.  Go (this project was created using Go 1.23.3)
2.  MySQL
3.  Docker
4.  Docker Compose
5.  GNU Make
6.  IDE

I think we can have a `docker-compose.yaml` (4) containing a container definition for (2), something like this ([reference](https://hub.docker.com/_/mysql)):

```yaml
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: example
```

And then, we can have a file `.env.example` containing something like:

```yaml
DB_USER=root
DB_PASSWORD=example
DB_HOST=localhost
DB_PORT=3306
DB_NAME=testdb
```

So, as a first-time contributor, I can just copy `.env.example` as `.env`, then do `docker-compose up`, and `go run main.go`. What do you think?
